IT-Academy-BCN/BusinessAssistantBCN-frontend2

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/core/components/header/header.component.html
- src/app/core/components/language-changer/language-changer.component.html
- src/app/core/components/language-changer/language-changer.component.ts
- src/app/core/components/language-changer/language-changer.module.ts
- src/app/core/core.module.ts
- component with material design
- set up transaltion services
> set up language changer

- src/app/shared/model/basic-business.interface.ts
- src/app/shared/model/economic-activity.interface.ts
- src/app/shared/model/zone.interface.ts
#21 Adds essential models for environments
> feature:Create environment models

- src/app/app.module.ts
- src/app/core/components/language-changer/language-changer.module.ts
- src/app/core/core.module.ts
- src/app/shared/translate/i18-tranlsate.module.ts
> 12 translation

- README.md
> Folder structure in README.md

- src/app/app.component.spec.ts
- src/app/core/components/header/animation/header.animation.ts
- src/app/core/components/header/header.component.html
- src/app/core/components/header/header.component.scss
- src/app/core/components/header/header.component.spec.ts
- src/app/core/components/header/header.component.ts
- src/app/core/components/header/header.module.ts
- src/app/core/components/language-changer/language-changer.component.html
- src/app/core/components/language-changer/language-changer.component.scss
- src/app/core/components/language-changer/language-changer.module.ts
- src/app/core/core.module.ts
- src/app/features/virtual-assistant/page-routing/virtual-assistant-page.component.html
- src/index.html
- src/styles.scss
- src/styles/_background-color.scss
- src/styles/_font-color.scss
- src/styles/_text.scss
header component y test completos
> 8 header #8

- src/app/shared/components/babcn-accordion/babcn-accordion.module.ts
- src/app/shared/components/babcn-accordion/component/babcn-accordion.component.html
- src/app/shared/components/babcn-list/babcn-list.module.ts
- src/app/shared/components/babcn-list/component/babcn-list.component.html
- src/app/shared/components/babcn-tree/babcn-tree.module.ts
- src/app/shared/components/babcn-tree/component/babcn-tree.component.html
> Módulo i18-translate en componentes babcn

- src/app/core/components/language-changer/language-changer.component.ts
- src/app/core/components/language-changer/language-changer.interface.ts
- src/app/core/components/language-changer/language-changer.spec.ts
added testing.
created enum type as a model for language parameter. Only three options will be able to be passed as a parameter.
> 14 Language Changer Testing

- src/app/app.module.ts
- src/app/features/home/components/home.component.html
- src/app/features/home/components/home.component.spec.ts
- src/app/features/home/components/home.component.ts
- src/app/features/home/home.module.ts
- src/app/features/my-environment/my-environment.module.ts
- src/app/features/my-environment/pages/my-environment-page/my-environment-page.component.html
- src/app/features/my-environment/pages/my-environment-page/my-environment-page.component.spec.ts
- src/app/features/my-environment/pages/my-environment-page/my-environment-page.component.ts
- src/app/features/my-environment/pages/my-environment-result/my-environment-result.component.html
- src/app/features/my-environment/pages/my-environment-result/my-environment-result.component.spec.ts
- src/app/features/my-environment/pages/my-environment-result/my-environment-result.component.ts
- src/app/features/my-environment/pages/my-environment-search/my-environment-search.component.html
- src/app/features/my-environment/pages/my-environment-search/my-environment-search.component.spec.ts
- src/app/features/my-environment/pages/my-environment-search/my-environment-search.component.ts
- src/app/features/my-environment/services/my-environment.service.spec.ts
- src/app/features/my-environment/services/my-environment.service.ts
- src/app/features/users/components/login/login.component.html
- src/app/features/users/components/login/login.component.spec.ts
- src/app/features/users/components/login/login.component.ts
- src/app/features/users/components/register/register.component.html
- src/app/features/users/components/register/register.component.spec.ts
- src/app/features/users/components/register/register.component.ts
- src/app/features/users/services/auth.service.spec.ts
- src/app/features/users/services/auth.service.ts
- src/app/features/users/users.module.ts
- Creación componente home dentro del módulo home.
- Creación módulo users, los componentes register y login, y capa de servicios
- Creación módulo my-environment, los componentes page, search y result, y capa de servicios
> 66 Creación módulos

- src/app/services/shared/breakpoint/BreakpointServiceReadme.md
- src/app/services/shared/breakpoint/breakpoint.service.ts
> add method getCurrentScreenSize

- src/app/features/my-environment/services/components/big-malls.service.ts
Prueba implementación service layer del proyecto anterior.
> add my-environment/service/components/big-malls

- src/app/features/home/components/header/header.component.ts
- src/app/features/home/components/info/info.component.ts
- src/app/features/home/components/presentation/presentation.component.html
- src/app/features/home/components/presentation/presentation.component.scss
- src/app/features/home/components/presentation/presentation.component.ts
- src/app/features/home/home.module.ts
- src/app/features/home/page/home.component.html
- src/app/features/my-environment/pages/my-environment-page/my-environment-page.component.ts
- src/app/features/virtual-assistant/page-routing/virtual-assistant-page.component.ts
- src/app/shared/components/babcn-tree/component/babcn-tree.component.scss
- src/styles/_material.scss
> home presentation & theming material

- src/app/features/home/components/header/header.component.scss
> escalado imagen home

- src/app/core/layout/header/header.component.ts
- src/app/features/home/components/info/info.component.html
- src/app/features/home/components/presentation/presentation.component.html
- src/app/features/home/components/presentation/presentation.component.scss
- src/app/features/home/components/presentation/presentation.component.ts
> enmudecimiento animación logo y algunos ajustes en home

- src/app/features/my-environment/pages/my-environment-page/my-environment-page.component.html
> navegabilidad my-environment corregida

- src/app/features/my-environment/my-environment.module.ts
- src/app/features/my-environment/pages/my-environment-page/my-environment-page.component.html
- src/app/features/my-environment/pages/my-environment-search/my-environment-search.component.html
- src/app/features/my-environment/pages/my-environment-search/my-environment-search.component.ts
- src/app/features/virtual-assistant/page-contents/virtual-assistant-main-content/component/virtual-assistant-main-content.component.html
- src/app/features/virtual-assistant/page-contents/virtual-assistant-main-content/component/virtual-assistant-main-content.component.scss
- src/styles.scss
- src/styles/_container.scss
> maquetación my-environment-search

- contributors.txt
Fisrt pull request in order to add a contributor to the develop branch
> add to contributors.txt

- src/app/core/layout/header/header.component.ts
Automatic Test #155 now passes.
> Fixed Automated Test #155

- src/app/core/core.module.ts
- src/app/core/layout/header/header.component.ts
- src/app/core/layout/language-changer/language-changer.spec.ts
Provided fix for error 161 per:
https://stackoverflow.com/questions/51364455/typeerror-this-handler-handle-is-not-a-function-error
And:
https://www.angularjswiki.com/angular/no-provider-for-httpclient/
> Feature test161 fix

- src/app/app.module.ts
- src/app/shared/components/babcn-title/babcn-title.module.ts
- src/app/shared/components/babcn-title/component/babcn-title.component.spec.ts
- src/app/shared/components/babcn-title/component/babcn-title.component.ts
- src/app/shared/shared.module.ts
Fixed Unit Test 160 - Test Error: BabcnTitleComponent > should create
by applying fix from this link: 
https://github.com/angular/angular/issues/47742
> fixed unit test 160

- src/app/features/my-environment/pages/my-environment-page/my-environment-page.component.html
- src/app/features/my-environment/pages/my-environment-page/my-environment-page.component.ts
Links from my enviromments page are hide
> hide no working links

- src/app/core/layout/header/header.component.html
- src/app/core/layout/header/header.component.ts
#248 
At header component, added language buttons to hamburger menu
- implemented translate services and language model
- language buttons in hamburger menu match Frontend 1 implementation
> added languages to hamburger menu

- src/app/features/my-environment/components/search-and-result/search-and-result.component.ts
- src/app/features/my-environment/services/my-environment.service.ts
- src/app/features/users/components/login-modal/login-modal.component.html
- src/app/features/users/components/login-modal/login-modal.component.spec.ts
- src/app/features/users/components/login-modal/login-modal.component.ts
- src/app/features/users/services/auth.service.ts
- src/app/services/common/common.service.ts
- src/app/shared/components/babcn-accordion/component/babcn-accordion.component.ts
- src/app/shared/models/common/activities.model.ts
- src/app/shared/models/common/login.model.ts
- src/app/shared/models/common/signup.model.ts
- src/app/shared/models/common/zones.model.ts
1-common.service.ts
Zones and Activities models were created
2-my-environment.service.ts
cannot correct any type in :
getResults(businessModelSearch: MyEnvironmentSearch): Observable<any> 
since the service  launchs a bad request
3-auth.service.ts
Login and Singup models Should be modified once service login and signup are operative
4-jwt-interceptor.service.ts
the HttpRequest<any> still remains uncathegorized
5-babcn-accordion.component.ts
dataOutput: string[]
dataInput: Category[]
> correct "any" types

- src/app/features/virtual-assistant/page-contents/virtual-assistant-main-content/component/virtual-assistant-main-content.component.html
- src/app/features/virtual-assistant/page-contents/virtual-assistant-main-content/component/virtual-assistant-main-content.component.ts
- src/app/shared/components/babcn-buttons-container/component/babcn-buttons-container.component.html
- src/app/shared/components/babcn-buttons-container/component/babcn-buttons-container.component.ts
Feature #272 
- Botón 'save' visible // activo -> lanza diálogo login // si user no ha iniciado sesión.
- Botón 'save' desaparece sí user ha iniciado sesión. 
Funcionalidad implementada a medias, a la espera de tener un modelo de "user"  donde poder verificar su inicio de sesión.
> Assistant: Botón 'Save'

- src/app/features/my-environment/components/search-and-result/search-and-result.component.html
- src/app/features/my-environment/components/search-and-result/search-and-result.component.scss
- src/app/features/my-environment/components/search-and-result/search-and-result.component.ts
- src/app/features/my-environment/services/mapbox-markers.service.spec.ts
- src/app/features/my-environment/services/mapbox-markers.service.ts
- src/app/shared/components/mapbox/mapbox.component.ts
#281 
My Environment Results:
- Right canvas now matches left canvas size
- MailTo link implemented on business emails
- Web Link to new tab implemented on business website
- Marker changes color to black when user clicks on business title and map centers on the selected marker
- Created Marker Service which uses Rxjs Subject and data setter
- Mapbox component subscribes to Subject in Markers Services
- Search and Result Component implements click event on business title that updates Marker Service's Subject.
> Finished Mapbox improvements
